export const initialFormData = {
  firstName: {
    id: "firstName",
    label: "First Name",
    type: "text",
    placeholder: "Enter First Name...",
    value: "",
    isError: false,
    errorMessage: "First Name can not be empty",
  },
  lastName: {
    id: "lastName",
    label: "Last Name",
    type: "text",
    placeholder: "Enter Last Name...",
    value: "",
    isError: false,
    errorMessage: "Last Name can not be empty",
  },
  email: {
    id: "email",
    label: "Email",
    type: "email",
    placeholder: "Enter email",
    value: "",
    isError: false,
    errorMessage: "Email can not be empty",
  },
  password: {
    id: "password",
    label: "Password",
    type: "text",
    placeholder: "Enter Password",
    value: "",
    isError: false,
    errorMessage: "Password can not be empty",
  },
  confirmPassword: {
    id: "confirmPassword",
    label: "Confirm Password",
    type: "text",
    placeholder: "Confirm Password",
    value: "",
    isError: false,
    errorMessage: "Password can not be empty",
  },
};
